server:
  port: 10086


spring:
  application:
    name: ly-registry

eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka
    register-with-eureka: false
    fetch-registry: false